import { resolve } from "path";
import { defineConfig } from "vite";
import dts from "vite-plugin-dts";

const entryPoints = {
  "index": resolve(__dirname, 'src/index.ts'),
  "db": resolve(__dirname, 'src/db/index.ts'),
  "fs": resolve(__dirname, 'src/fs/index.ts'),
  "http": resolve(__dirname, 'src/http/index.ts'),
  "job": resolve(__dirname, 'src/job/index.ts'),
  "kv": resolve(__dirname, 'src/kv/index.ts'),
};

export default defineConfig({
  build: {
    outDir: "./dist",
    minify: false,
    lib: {
      entry: Object.values(entryPoints),
      formats: ["es"],
    },
    rollupOptions: {
      plugins: [
        dts({
          // NOTE: We could try to roll-up all types into a single declaration file per module,
          // however due to cross-module deps this leads to duplicate type declarations,
          // e.g. HttpHandlerInterface and all its dependent types are declared both in the
          // "index" and "http" modules.
          // This confuses the heck out of tsc for downstream users of this library.
          // Maybe there are some rollup(Config|Options) that woudl address this :shrug:.
          rollupTypes: false,
          // NOTE: Include .d.ts files generated by `jco`.
          copyDtsFiles: true,
          // NOTE: The .d.ts files generated by `jco` contain dynamic imports.
          staticImport: true,
        }),
      ],
      input: entryPoints,
      output: {
        entryFileNames: "[name].js",
      },
      external: [
        /^wasi:.*/,
        /^trailbase:.*/,
      ],
    },
  },
});
