apiVersion: v1
kind: Service
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-issuer
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ./.helm/templates
    kompose.controller.type: statefulset
    kompose.service.expose: rabbitmq.argiago.test
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: rabbitmq-secret
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 15672
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}
