x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${LOG_MAX_SIZE:-10m}"
    max-file: "${LOG_MAX_FILE:-3}"
    compress: "${LOG_COMPRESS:-true}"

services:
  argiago-web:
    container_name: argiago-web
    image: argiago
    build: .
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 4000:4000
    volumes:
      - argiago-data:/workspace/app/traildepot/data
      - argiago-backups:/workspace/app/traildepot/backups
      - argiago-secrets:/workspace/app/traildepot/secrets
      - argiago-uploads:/workspace/app/traildepot/uploads

volumes:
  argiago-data:
    name: argiago-data
  argiago-backups:
    name: argiago-backups
  argiago-secrets:
    name: argiago-secrets
  argiago-uploads:
    name: argiago-uploads