FROM rust:alpine AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apk update && apk add musl musl-dev libressl-dev

ENV APP=avatar-uploader APP_FILE=avatar_uploader

WORKDIR /source/${APP}

COPY Cargo.toml Cargo.toml

RUN mkdir src/ && echo "fn main() {println!(\"if you see this, the build broke\")}" > src/main.rs

RUN cargo build --target=x86_64-unknown-linux-musl

RUN rm ./src/*.rs && rm ./target/x86_64-unknown-linux-musl/debug/deps/${APP_FILE}*

COPY ./src/ ./src/

RUN cargo build --target=x86_64-unknown-linux-musl


FROM rust:alpine AS publish

RUN apk --no-cache add curl

WORKDIR /app

ENV APP=avatar-uploader

COPY --from=builder /source/${APP}/target/x86_64-unknown-linux-musl/debug/${APP} ./

# ENTRYPOINT ["./avatar-uploader"]

ENTRYPOINT ["tail", "-f", "/dev/null"]