apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-issuer
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ./.helm/templates
    kompose.service.expose: comment-user-filter.argiago.test
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: comment-user-filter-secret
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: comment-user-filter
  name: comment-user-filter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: comment-user-filter
  strategy: {}
  template:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: cert-manager-issuer
        kompose.cmd: kompose convert -f docker-compose.dev.yml -o ./.helm/templates
        kompose.service.expose: comment-user-filter.argiago.test
        kompose.service.expose.ingress-class-name: nginx
        kompose.service.expose.tls-secret: comment-user-filter-secret
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/argiago-network: "true"
        io.kompose.service: comment-user-filter
    spec:
      containers:
        - env:
            - name: DB_URL
              value: postgresql://postgres:postgres@${KEYCLOAKDB_SERVICE_HOST}:${KEYCLOAKDB_SERVICE_PORT}/postgres
            - name: ISSUER
              value: https://keycloak.argiago.test/realms/argiago-test
            - name: REALM
              value: argiago-test
          image: {{ .Values.werf.image.comment_user_filter }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/healthcheck
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
          name: comment-user-filter
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
