[frontend]
serve_from = "embedded"
password_auth_enabled = false

[trailbase.server]
site_url = "https://velora.ru"

[trailbase.auth]
disable_password_auth = true
enable_otp_signin = false

[components]
rebuild = false
refetch = false

[[components.items]]
name = "wcauth"
wasm = "wcauth.wasm"
source = { fetch = "https://github.com/zyrakq/wcauth/releases/latest/download/wcauth_component.wasm" }

