[server]
address = "0.0.0.0:4000"

[frontend]
serve_from = "disk"
watch = false
public_dir = ""

[mailcrab]
dev_intercept = false
path = "/_/mailcrab"
smtp_host = "127.0.0.1"
smtp_port = 1025

[trailbase.server]
application_name = "Argiago"
site_url = "http://localhost:4000"
logs_retention_sec = 604800

[trailbase.auth]
disable_password_auth = false
enable_otp_signin = false

[trailbase.auth.oidc0]
client_id = "argiago"
client_secret = ""
auth_url = "https://idm.argiago.ru/ui/oauth2"
token_url = "https://idm.argiago.ru/oauth2/token"
user_api_url = "https://idm.argiago.ru/oauth2/openid/argiago/userinfo"

[trailbase.smtp]
sender_name = "Argiago Notifications"
sender_address = "notifications@argiago.ru"

[components]
rebuild = false
refetch = false

[[components.items]]
name = "auth_ui"
wasm = "auth_ui_component.wasm"
source = { fetch = "trailbase/auth_ui" }

# [[components.items]]
# name = "trail_auth"
# wasm = "trail_auth_component.wasm"
# source = { build = "trail-auth-component" }
