[frontend]
serve_from = "disk"
watch = true
password_auth_enabled = true

[mailcrab]
dev_intercept = true

[components]
rebuild = true
refetch = false

[[components.items]]
name = "trail_auth"
wasm = "trail_auth_component.wasm"
source = { build = "trail-auth-component" }
