[frontend]
serve_from = "disk"
watch = true
password_auth_enabled = true

[mailcrab]
dev_intercept = true

[components]
rebuild = true
refetch = false

# [[components.items]]
# name = "auth_ui"
# wasm = "auth_ui.wasm"
# source = { zip_name = "auth_ui_component.wasm",  fetch = "https://github.com/trailbaseio/trailbase/releases/download/v0.28.6/trailbase_v0.28.6_wasm_auth_ui.zip" }