[frontend]
serve_from = "disk"
watch = true
password_auth_enabled = true

[mailcrab]
dev_intercept = true

[components]
rebuild = true
refetch = false

# [[components.items]]
# name = "trailbase-auth-ui"
# wasm = "trailbase_auth_ui.wasm"
# source = { zip_name = "trailbase_auth_ui_component.wasm",  fetch = "https://github.com/trailbaseio/trailbase/releases/download/v0.29.0/trailbase_v0.29.0_wasm_auth_ui.zip" }