[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
env_logger = { workspace = true }
tokio-rustls = { workspace = true }
pretty_env_logger = { workspace = true }
trailbase = { workspace = true }
dotenvy = { workspace = true }
config = { workspace = true }
mailcrab-server = { workspace = true }
rust-embed = { workspace = true }
mime_guess = "2"
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }
log = "0.4"
trailbase-sqlite = { path = "../vendor/trailbase/crates/sqlite", default-features = false }
uuid = { version = "1", features = ["v4"] }
zip = { version = "8.1.0", default-features = false, features = ["deflate"] }

[dev-dependencies]
indoc = "2"
tempfile = "3"

[build-dependencies]
config = { workspace = true }
serde = { workspace = true }
