[build]
target-dir = "target/builder"
jobs = 4
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold", "-C", "link-arg=-Wl,--icf=all"]

[env]
APP_SKIP_WASM = "0"
CARGO_TARGET_DIR = "target/builder"
