apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-issuer
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ./.helm/templates
    kompose.service.expose: post-requester.argiago.test
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: post-requester-secret
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: post-requester
  name: post-requester
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-requester
  strategy: {}
  template:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: cert-manager-issuer
        kompose.cmd: kompose convert -f docker-compose.dev.yml -o ./.helm/templates
        kompose.service.expose: post-requester.argiago.test
        kompose.service.expose.ingress-class-name: nginx
        kompose.service.expose.tls-secret: post-requester-secret
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/argiago-network: "true"
        io.kompose.service: post-requester
    spec:
      containers:
        - env:
            - name: COLLECTION_NAME
              value: post
            - name: DB_NAME
              value: post_store
            - name: DB_URL
              value: mongodb://root:root@${MONGO_SERVICE_HOST}:${MONGO_SERVICE_PORT}
            - name: ISSUER
              value: https://keycloak.argiago.test/realms/argiago-test
          image: {{ .Values.werf.image.post_requester }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/healthcheck
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
          name: post-requester
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
