version: "3.8"

services:
  keycloakdb:
    container_name: keycloakdb
    image: postgres:12.9
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh", "-c", "exec pg_isready -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-argiago-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/health/ready" ]
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - 8585:8080
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: token-exchange
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_HTTP_ENABLED: 'true'
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_CACHE_STACK: tcp
      KC_HEALTH_ENABLED: 'true'
    configs:
      - source: argiago-realm
        target: /opt/keycloak/data/import/argiago.json
      - source: argiago-test-realm
        target: /opt/keycloak/data/import/argiago-test.json
    volumes:
      - ./providers/lnurl-auth.jar:/opt/keycloak/providers/lnurl-auth.jar
      - ./providers/keywind.jar:/opt/keycloak/providers/keywind.jar
      - ./theme/:/opt/keycloak/themes/
    command:
      - "start"
      - "--http-port 8080"
      - "--proxy=edge"
      - "--import-realm"
      - "--spi-theme-static-max-age=-1"
      - "--spi-theme-cache-themes=false"
      - "--spi-theme-cache-templates=false"
    depends_on:
      - keycloakdb
    networks:
      - keycloak-argiago-network

configs:
  argiago-realm:
    file: ./import/argiago.json
  argiago-test-realm:
    file: ./import/argiago.json

volumes:
  keycloakdb:
    driver: local

networks:
  keycloak-argiago-network:
    driver: bridge