// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.21.12
// source: config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "config";

export enum SmtpEncryption {
  SMTP_ENCRYPTION_UNDEFINED = 0,
  SMTP_ENCRYPTION_NONE = 1,
  SMTP_ENCRYPTION_STARTTLS = 2,
  SMTP_ENCRYPTION_TLS = 3,
  UNRECOGNIZED = -1,
}

export function smtpEncryptionFromJSON(object: any): SmtpEncryption {
  switch (object) {
    case 0:
    case "SMTP_ENCRYPTION_UNDEFINED":
      return SmtpEncryption.SMTP_ENCRYPTION_UNDEFINED;
    case 1:
    case "SMTP_ENCRYPTION_NONE":
      return SmtpEncryption.SMTP_ENCRYPTION_NONE;
    case 2:
    case "SMTP_ENCRYPTION_STARTTLS":
      return SmtpEncryption.SMTP_ENCRYPTION_STARTTLS;
    case 3:
    case "SMTP_ENCRYPTION_TLS":
      return SmtpEncryption.SMTP_ENCRYPTION_TLS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SmtpEncryption.UNRECOGNIZED;
  }
}

export function smtpEncryptionToJSON(object: SmtpEncryption): string {
  switch (object) {
    case SmtpEncryption.SMTP_ENCRYPTION_UNDEFINED:
      return "SMTP_ENCRYPTION_UNDEFINED";
    case SmtpEncryption.SMTP_ENCRYPTION_NONE:
      return "SMTP_ENCRYPTION_NONE";
    case SmtpEncryption.SMTP_ENCRYPTION_STARTTLS:
      return "SMTP_ENCRYPTION_STARTTLS";
    case SmtpEncryption.SMTP_ENCRYPTION_TLS:
      return "SMTP_ENCRYPTION_TLS";
    case SmtpEncryption.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OAuthProviderId {
  OAUTH_PROVIDER_ID_UNDEFINED = 0,
  TEST = 1,
  OIDC0 = 2,
  APPLE = 9,
  DISCORD = 10,
  GITLAB = 11,
  GOOGLE = 12,
  FACEBOOK = 13,
  MICROSOFT = 14,
  TWITCH = 15,
  YANDEX = 16,
  GITHUB = 17,
  UNRECOGNIZED = -1,
}

export function oAuthProviderIdFromJSON(object: any): OAuthProviderId {
  switch (object) {
    case 0:
    case "OAUTH_PROVIDER_ID_UNDEFINED":
      return OAuthProviderId.OAUTH_PROVIDER_ID_UNDEFINED;
    case 1:
    case "TEST":
      return OAuthProviderId.TEST;
    case 2:
    case "OIDC0":
      return OAuthProviderId.OIDC0;
    case 9:
    case "APPLE":
      return OAuthProviderId.APPLE;
    case 10:
    case "DISCORD":
      return OAuthProviderId.DISCORD;
    case 11:
    case "GITLAB":
      return OAuthProviderId.GITLAB;
    case 12:
    case "GOOGLE":
      return OAuthProviderId.GOOGLE;
    case 13:
    case "FACEBOOK":
      return OAuthProviderId.FACEBOOK;
    case 14:
    case "MICROSOFT":
      return OAuthProviderId.MICROSOFT;
    case 15:
    case "TWITCH":
      return OAuthProviderId.TWITCH;
    case 16:
    case "YANDEX":
      return OAuthProviderId.YANDEX;
    case 17:
    case "GITHUB":
      return OAuthProviderId.GITHUB;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OAuthProviderId.UNRECOGNIZED;
  }
}

export function oAuthProviderIdToJSON(object: OAuthProviderId): string {
  switch (object) {
    case OAuthProviderId.OAUTH_PROVIDER_ID_UNDEFINED:
      return "OAUTH_PROVIDER_ID_UNDEFINED";
    case OAuthProviderId.TEST:
      return "TEST";
    case OAuthProviderId.OIDC0:
      return "OIDC0";
    case OAuthProviderId.APPLE:
      return "APPLE";
    case OAuthProviderId.DISCORD:
      return "DISCORD";
    case OAuthProviderId.GITLAB:
      return "GITLAB";
    case OAuthProviderId.GOOGLE:
      return "GOOGLE";
    case OAuthProviderId.FACEBOOK:
      return "FACEBOOK";
    case OAuthProviderId.MICROSOFT:
      return "MICROSOFT";
    case OAuthProviderId.TWITCH:
      return "TWITCH";
    case OAuthProviderId.YANDEX:
      return "YANDEX";
    case OAuthProviderId.GITHUB:
      return "GITHUB";
    case OAuthProviderId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * What user identifier to use for new user registrations as well as
 * change-(email|username).
 *
 * NOTE: W/o email there's no way to contact users.
 */
export enum UserIdentifier {
  USER_IDENTIFIER_UNDEFINED = 0,
  /** ONLY_EMAIL - / Only email. Doesn't work for anonymous login. */
  ONLY_EMAIL = 1,
  /** ONLY_USERNAME - / Only username. No email allowed. */
  ONLY_USERNAME = 2,
  /** REQUIRE_EMAIL - / Requires email and allows an optional username. */
  REQUIRE_EMAIL = 3,
  /** REQUIRE_USERNAME - / Requires username and allows an optional email. */
  REQUIRE_USERNAME = 4,
  /** REQUIRE_EMAIL_AND_USERNAME - / Requires both email and username. */
  REQUIRE_EMAIL_AND_USERNAME = 5,
  UNRECOGNIZED = -1,
}

export function userIdentifierFromJSON(object: any): UserIdentifier {
  switch (object) {
    case 0:
    case "USER_IDENTIFIER_UNDEFINED":
      return UserIdentifier.USER_IDENTIFIER_UNDEFINED;
    case 1:
    case "ONLY_EMAIL":
      return UserIdentifier.ONLY_EMAIL;
    case 2:
    case "ONLY_USERNAME":
      return UserIdentifier.ONLY_USERNAME;
    case 3:
    case "REQUIRE_EMAIL":
      return UserIdentifier.REQUIRE_EMAIL;
    case 4:
    case "REQUIRE_USERNAME":
      return UserIdentifier.REQUIRE_USERNAME;
    case 5:
    case "REQUIRE_EMAIL_AND_USERNAME":
      return UserIdentifier.REQUIRE_EMAIL_AND_USERNAME;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserIdentifier.UNRECOGNIZED;
  }
}

export function userIdentifierToJSON(object: UserIdentifier): string {
  switch (object) {
    case UserIdentifier.USER_IDENTIFIER_UNDEFINED:
      return "USER_IDENTIFIER_UNDEFINED";
    case UserIdentifier.ONLY_EMAIL:
      return "ONLY_EMAIL";
    case UserIdentifier.ONLY_USERNAME:
      return "ONLY_USERNAME";
    case UserIdentifier.REQUIRE_EMAIL:
      return "REQUIRE_EMAIL";
    case UserIdentifier.REQUIRE_USERNAME:
      return "REQUIRE_USERNAME";
    case UserIdentifier.REQUIRE_EMAIL_AND_USERNAME:
      return "REQUIRE_EMAIL_AND_USERNAME";
    case UserIdentifier.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SystemJobId {
  SYSTEM_JOB_ID_UNDEFINED = 0,
  BACKUP = 1,
  HEARTBEAT = 2,
  LOG_CLEANER = 3,
  AUTH_CLEANER = 4,
  QUERY_OPTIMIZER = 5,
  FILE_DELETIONS = 6,
  ANONYMOUS_CLEANER = 7,
  UNRECOGNIZED = -1,
}

export function systemJobIdFromJSON(object: any): SystemJobId {
  switch (object) {
    case 0:
    case "SYSTEM_JOB_ID_UNDEFINED":
      return SystemJobId.SYSTEM_JOB_ID_UNDEFINED;
    case 1:
    case "BACKUP":
      return SystemJobId.BACKUP;
    case 2:
    case "HEARTBEAT":
      return SystemJobId.HEARTBEAT;
    case 3:
    case "LOG_CLEANER":
      return SystemJobId.LOG_CLEANER;
    case 4:
    case "AUTH_CLEANER":
      return SystemJobId.AUTH_CLEANER;
    case 5:
    case "QUERY_OPTIMIZER":
      return SystemJobId.QUERY_OPTIMIZER;
    case 6:
    case "FILE_DELETIONS":
      return SystemJobId.FILE_DELETIONS;
    case 7:
    case "ANONYMOUS_CLEANER":
      return SystemJobId.ANONYMOUS_CLEANER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SystemJobId.UNRECOGNIZED;
  }
}

export function systemJobIdToJSON(object: SystemJobId): string {
  switch (object) {
    case SystemJobId.SYSTEM_JOB_ID_UNDEFINED:
      return "SYSTEM_JOB_ID_UNDEFINED";
    case SystemJobId.BACKUP:
      return "BACKUP";
    case SystemJobId.HEARTBEAT:
      return "HEARTBEAT";
    case SystemJobId.LOG_CLEANER:
      return "LOG_CLEANER";
    case SystemJobId.AUTH_CLEANER:
      return "AUTH_CLEANER";
    case SystemJobId.QUERY_OPTIMIZER:
      return "QUERY_OPTIMIZER";
    case SystemJobId.FILE_DELETIONS:
      return "FILE_DELETIONS";
    case SystemJobId.ANONYMOUS_CLEANER:
      return "ANONYMOUS_CLEANER";
    case SystemJobId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * / Sqlite specific (as opposed to standard SQL) constrained-violation
 * / resolution strategy upon insert.
 */
export enum ConflictResolutionStrategy {
  CONFLICT_RESOLUTION_STRATEGY_UNDEFINED = 0,
  /** ABORT - / SQL default: Keep transaction open and abort the current statement. */
  ABORT = 1,
  /**
   * IGNORE - / Skip the statement and continue. Mostly matters in the context of batches
   * / and transaction. Rather than aborting, subsequent operations will
   * / continue.
   */
  IGNORE = 4,
  /**
   * REPLACE - / Replaces the conflicting row in case of a collision (e.g. unique
   * / constraint).
   */
  REPLACE = 5,
  UNRECOGNIZED = -1,
}

export function conflictResolutionStrategyFromJSON(object: any): ConflictResolutionStrategy {
  switch (object) {
    case 0:
    case "CONFLICT_RESOLUTION_STRATEGY_UNDEFINED":
      return ConflictResolutionStrategy.CONFLICT_RESOLUTION_STRATEGY_UNDEFINED;
    case 1:
    case "ABORT":
      return ConflictResolutionStrategy.ABORT;
    case 4:
    case "IGNORE":
      return ConflictResolutionStrategy.IGNORE;
    case 5:
    case "REPLACE":
      return ConflictResolutionStrategy.REPLACE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConflictResolutionStrategy.UNRECOGNIZED;
  }
}

export function conflictResolutionStrategyToJSON(object: ConflictResolutionStrategy): string {
  switch (object) {
    case ConflictResolutionStrategy.CONFLICT_RESOLUTION_STRATEGY_UNDEFINED:
      return "CONFLICT_RESOLUTION_STRATEGY_UNDEFINED";
    case ConflictResolutionStrategy.ABORT:
      return "ABORT";
    case ConflictResolutionStrategy.IGNORE:
      return "IGNORE";
    case ConflictResolutionStrategy.REPLACE:
      return "REPLACE";
    case ConflictResolutionStrategy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum PermissionFlag {
  PERMISSION_FLAG_UNDEFINED = 0,
  /** CREATE - Database record insert. */
  CREATE = 1,
  /** READ - Database record read/list, i.e. select. */
  READ = 2,
  /** UPDATE - Database record update. */
  UPDATE = 4,
  /** DELETE - Database record delete. */
  DELETE = 8,
  /** SCHEMA - / Lookup JSON schema for the given record api . */
  SCHEMA = 16,
  UNRECOGNIZED = -1,
}

export function permissionFlagFromJSON(object: any): PermissionFlag {
  switch (object) {
    case 0:
    case "PERMISSION_FLAG_UNDEFINED":
      return PermissionFlag.PERMISSION_FLAG_UNDEFINED;
    case 1:
    case "CREATE":
      return PermissionFlag.CREATE;
    case 2:
    case "READ":
      return PermissionFlag.READ;
    case 4:
    case "UPDATE":
      return PermissionFlag.UPDATE;
    case 8:
    case "DELETE":
      return PermissionFlag.DELETE;
    case 16:
    case "SCHEMA":
      return PermissionFlag.SCHEMA;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PermissionFlag.UNRECOGNIZED;
  }
}

export function permissionFlagToJSON(object: PermissionFlag): string {
  switch (object) {
    case PermissionFlag.PERMISSION_FLAG_UNDEFINED:
      return "PERMISSION_FLAG_UNDEFINED";
    case PermissionFlag.CREATE:
      return "CREATE";
    case PermissionFlag.READ:
      return "READ";
    case PermissionFlag.UPDATE:
      return "UPDATE";
    case PermissionFlag.DELETE:
      return "DELETE";
    case PermissionFlag.SCHEMA:
      return "SCHEMA";
    case PermissionFlag.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface EmailTemplate {
  subject?: string | undefined;
  body?: string | undefined;
}

export interface EmailConfig {
  smtpHost?: string | undefined;
  smtpPort?: number | undefined;
  smtpUsername?: string | undefined;
  smtpPassword?:
    | string
    | undefined;
  /** Which encryption method to use. STARTTLS by default. */
  smtpEncryption?: SmtpEncryption | undefined;
  senderName?: string | undefined;
  senderAddress?: string | undefined;
  userVerificationTemplate?: EmailTemplate | undefined;
  passwordResetTemplate?: EmailTemplate | undefined;
  changeEmailTemplate?: EmailTemplate | undefined;
  otpTemplate?: EmailTemplate | undefined;
}

export interface OAuthProviderConfig {
  clientId?: string | undefined;
  clientSecret?: string | undefined;
  providerId?:
    | OAuthProviderId
    | undefined;
  /**
   * Settings for generic OpenID Connect provider. Name is implicitly provided
   * via the `AuthConfig.oauth_provders` map key.
   */
  displayName?: string | undefined;
  authUrl?: string | undefined;
  tokenUrl?: string | undefined;
  userApiUrl?: string | undefined;
}

export interface AuthConfig {
  /** / Time-to-live in seconds for auth tokens. Default: 1h. */
  authTokenTtlSec?:
    | bigint
    | undefined;
  /** / Time-to-live in seconds for refresh tokens. Default: 30 days. */
  refreshTokenTtlSec?:
    | bigint
    | undefined;
  /** / Disables password-based sign-up. Does not affect already registered users. */
  disablePasswordAuth?:
    | boolean
    | undefined;
  /**
   * / Whether sign-in via OTP codes (e.g. sent via Email) should be allowed.
   * / This may be less secure since ultimately you're delegating operational
   * / security to a user's inbox.
   */
  enableOtpSignin?:
    | boolean
    | undefined;
  /**
   * / Allow the creation of ephemeral user-accounts, e.g. for a frictionless
   * / trial.
   */
  enableAnonymousSignin?:
    | boolean
    | undefined;
  /** / Minimal password length. Defaults to 8. */
  passwordMinimalLength?:
    | number
    | undefined;
  /** / Password must contain lower and upper-case letters. */
  passwordMustContainUpperAndLowerCase?:
    | boolean
    | undefined;
  /** / Password must contain digits in addition to alphabetic characters.. */
  passwordMustContainDigits?:
    | boolean
    | undefined;
  /** / Password must contain special, non-alphanumeric, characters. */
  passwordMustContainSpecialCharacters?:
    | boolean
    | undefined;
  /** / Map of configured OAuth providers. */
  oauthProviders: { [key: string]: OAuthProviderConfig };
  /**
   * / List of custom URI schemes allowed as auth redirects.
   * /
   * / This is useful for mobile apps, desktop or SPAs where an app registers a
   * / custom scheme for calls it wants to handle.
   */
  customUriSchemes: string[];
  /** / List of explicitly allowed redirect uris. */
  redirectUriAllowlist: string[];
  /**
   * / Policy covering user registration and change (username|email) flows around
   * / what user identifier is expected and accepted. Default: ONLY_EMAIL.
   */
  userIdentifier?: UserIdentifier | undefined;
}

export interface AuthConfig_OauthProvidersEntry {
  key: string;
  value: OAuthProviderConfig | undefined;
}

export interface S3StorageConfig {
  endpoint?: string | undefined;
  region?: string | undefined;
  bucketName?:
    | string
    | undefined;
  /** / S3 access key, a.k.a. username. */
  accessKey?:
    | string
    | undefined;
  /** / S3 secret access key, a.k.a. password. */
  secretAccessKey?: string | undefined;
}

export interface ServerConfig {
  /**
   * / Application name presented to users, e.g. when sending emails. Default:
   * / "TrailBase".
   */
  applicationName?:
    | string
    | undefined;
  /**
   * / Your final, deployed URL. This url is used to build canonical urls
   * / for emails, OAuth redirects, ... . Default: "http://localhost:4000".
   */
  siteUrl?:
    | string
    | undefined;
  /**
   * /  Max age of logs that will be retained during period logs cleanup. Note
   * /  that this implies that some older logs may persist until the cleanup job
   * /  reruns. Default: 7 days.
   */
  logsRetentionSec?:
    | bigint
    | undefined;
  /** / If present will use S3 setup over local file-system based storage. */
  s3StorageConfig?:
    | S3StorageConfig
    | undefined;
  /** / If enabled, batches of transactions can be submitted for atomic execution */
  enableRecordTransactions?:
    | boolean
    | undefined;
  /** / Request size limit, default: 10MB. */
  requestSizeLimitBytes?:
    | bigint
    | undefined;
  /**
   * / Limits the request per IP per second to auth POST APIs for abuse
   * / protection. If TrailBase is behind a proxy, make sure to set
   * / "X-Forwarded-For". Default: disabled.
   * /
   * / Note that login endpoints have additional fixed rate limits
   * / on a per credentials level.
   */
  authIpRateLimit?: number | undefined;
}

export interface SystemJob {
  /** / Identifies the system job by its id. */
  id?:
    | SystemJobId
    | undefined;
  /**
   * / Cron spec: shorthand or 7-components: (sec, min, hour, day of month, /
   * / month, day of week, year).
   */
  schedule?:
    | string
    | undefined;
  /** / Disable the system job. */
  disabled?: boolean | undefined;
}

export interface JobsConfig {
  /**
   * / System jobs overrides.
   * /
   * / NOTE: This is technically a map from id to config, however enums are not
   * / allowed as map keys.
   */
  systemJobs: SystemJob[];
}

export interface RecordApiConfig {
  /** / API name, i.e. unique name used to access data via HTTP. */
  name?:
    | string
    | undefined;
  /** / Referenced table to be exposed. */
  tableName?:
    | string
    | undefined;
  /**
   * / Attached databases - will `ATTACH <traildepot>/data/<name>.db AS <name>`.
   * / Can only reference configured databases.
   */
  attachedDatabases: string[];
  /** / Strategy to be used on insert if a table constraint is violated. */
  conflictResolution?:
    | ConflictResolutionStrategy
    | undefined;
  /**
   * / Fill columns referencing _user(id) automatically from current user's
   * / authentication context if present. Can be useful for static clients, such
   * / as HTML forms, otherwise it's recommended to have the client provide user
   * / ids explicitly and to keep this feature off.
   */
  autofillMissingUserIdColumns?:
    | boolean
    | undefined;
  /**
   * / Allow subscribing to data changes in realtime using SSE streaming.
   * /
   * / NOTE: If you're using a reverse proxy, this will likely require
   * / configuration changes to allow for server-side streaming HTTP, e.g.
   * / tell the proxy to keep listening and not cache.
   */
  enableSubscriptions?:
    | boolean
    | undefined;
  /** / Access control lists. */
  aclWorld: PermissionFlag[];
  aclAuthenticated: PermissionFlag[];
  /**
   * / Columns excluded from this API.
   * /
   * / Excluded columns are completely inaccessible via this API. This is
   * / different from columns with names prefixed by "_", which are considered
   * / hidden. This means they can still be inserted, updated and access checked
   * / unlike excluded columns.
   */
  excludedColumns: string[];
  /**
   * / Access rules to be evaluated on request. Expected to be valid SQL
   * / expression, where `SELECT <expr>` returns a unary boolean.
   * /
   * / The evaluator injects _USER_, _ROW_ and _REQ_ tables that can be
   * / used for validating access, e.g.:
   * /
   * /   _USER_.id = _REQ_.owner
   * /
   * / ensures that the value provided for the `owner` column during an insert
   * / matches the current authenticated user's id. One can also construct
   * / arbitrary validations including sub-queries, e.g.:
   * /
   * /   _USER_.id = _REQ_.owner AND EXISTS(SELECT FROM allowed WHERE
   * /   allowed.user = _USER_.id)
   */
  createAccessRule?: string | undefined;
  readAccessRule?: string | undefined;
  updateAccessRule?: string | undefined;
  deleteAccessRule?: string | undefined;
  schemaAccessRule?:
    | string
    | undefined;
  /**
   * / A list of foreign key columns that *can* be expanded on read/list, i.e.
   * / the foreign record will be inlined into the response. By default nothing
   * / is expanded.
   * /
   * / Only columns and foreign tables with names not starting with "_", i.e. are
   * / allowed to be expanded.
   */
  expand: string[];
  /** / Hard limit for listing records (default: 1024). */
  listingHardLimit?: bigint | undefined;
}

export interface JsonSchemaConfig {
  name?: string | undefined;
  schema?: string | undefined;
}

export interface DatabaseConfig {
  /** / Name will be used as <traildepot>/(data/<name>.db|migrations/<name>/). */
  name?: string | undefined;
}

export interface Config {
  /**
   * NOTE: These top-level fields currently have to be `required` due to the
   * overly simple approach on how we do config merging (from env vars and
   * vault).
   */
  email: EmailConfig | undefined;
  server: ServerConfig | undefined;
  auth: AuthConfig | undefined;
  jobs: JobsConfig | undefined;
  databases: DatabaseConfig[];
  recordApis: RecordApiConfig[];
  schemas: JsonSchemaConfig[];
}

function createBaseEmailTemplate(): EmailTemplate {
  return {};
}

export const EmailTemplate: MessageFns<EmailTemplate> = {
  encode(message: EmailTemplate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subject !== undefined && message.subject !== "") {
      writer.uint32(10).string(message.subject);
    }
    if (message.body !== undefined && message.body !== "") {
      writer.uint32(18).string(message.body);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailTemplate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailTemplate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.body = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailTemplate {
    return {
      subject: isSet(object.subject) ? globalThis.String(object.subject) : undefined,
      body: isSet(object.body) ? globalThis.String(object.body) : undefined,
    };
  },

  toJSON(message: EmailTemplate): unknown {
    const obj: any = {};
    if (message.subject !== undefined && message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.body !== undefined && message.body !== "") {
      obj.body = message.body;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailTemplate>, I>>(base?: I): EmailTemplate {
    return EmailTemplate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailTemplate>, I>>(object: I): EmailTemplate {
    const message = createBaseEmailTemplate();
    message.subject = object.subject ?? "";
    message.body = object.body ?? "";
    return message;
  },
};

function createBaseEmailConfig(): EmailConfig {
  return {};
}

export const EmailConfig: MessageFns<EmailConfig> = {
  encode(message: EmailConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.smtpHost !== undefined && message.smtpHost !== "") {
      writer.uint32(10).string(message.smtpHost);
    }
    if (message.smtpPort !== undefined && message.smtpPort !== 0) {
      writer.uint32(16).uint32(message.smtpPort);
    }
    if (message.smtpUsername !== undefined && message.smtpUsername !== "") {
      writer.uint32(26).string(message.smtpUsername);
    }
    if (message.smtpPassword !== undefined && message.smtpPassword !== "") {
      writer.uint32(34).string(message.smtpPassword);
    }
    if (message.smtpEncryption !== undefined && message.smtpEncryption !== 0) {
      writer.uint32(40).int32(message.smtpEncryption);
    }
    if (message.senderName !== undefined && message.senderName !== "") {
      writer.uint32(90).string(message.senderName);
    }
    if (message.senderAddress !== undefined && message.senderAddress !== "") {
      writer.uint32(98).string(message.senderAddress);
    }
    if (message.userVerificationTemplate !== undefined) {
      EmailTemplate.encode(message.userVerificationTemplate, writer.uint32(170).fork()).join();
    }
    if (message.passwordResetTemplate !== undefined) {
      EmailTemplate.encode(message.passwordResetTemplate, writer.uint32(178).fork()).join();
    }
    if (message.changeEmailTemplate !== undefined) {
      EmailTemplate.encode(message.changeEmailTemplate, writer.uint32(186).fork()).join();
    }
    if (message.otpTemplate !== undefined) {
      EmailTemplate.encode(message.otpTemplate, writer.uint32(194).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmailConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmailConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.smtpHost = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.smtpPort = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.smtpUsername = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.smtpPassword = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.smtpEncryption = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.senderName = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.senderAddress = reader.string();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.userVerificationTemplate = EmailTemplate.decode(reader, reader.uint32());
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.passwordResetTemplate = EmailTemplate.decode(reader, reader.uint32());
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.changeEmailTemplate = EmailTemplate.decode(reader, reader.uint32());
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.otpTemplate = EmailTemplate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmailConfig {
    return {
      smtpHost: isSet(object.smtpHost)
        ? globalThis.String(object.smtpHost)
        : isSet(object.smtp_host)
        ? globalThis.String(object.smtp_host)
        : undefined,
      smtpPort: isSet(object.smtpPort)
        ? globalThis.Number(object.smtpPort)
        : isSet(object.smtp_port)
        ? globalThis.Number(object.smtp_port)
        : undefined,
      smtpUsername: isSet(object.smtpUsername)
        ? globalThis.String(object.smtpUsername)
        : isSet(object.smtp_username)
        ? globalThis.String(object.smtp_username)
        : undefined,
      smtpPassword: isSet(object.smtpPassword)
        ? globalThis.String(object.smtpPassword)
        : isSet(object.smtp_password)
        ? globalThis.String(object.smtp_password)
        : undefined,
      smtpEncryption: isSet(object.smtpEncryption)
        ? smtpEncryptionFromJSON(object.smtpEncryption)
        : isSet(object.smtp_encryption)
        ? smtpEncryptionFromJSON(object.smtp_encryption)
        : undefined,
      senderName: isSet(object.senderName)
        ? globalThis.String(object.senderName)
        : isSet(object.sender_name)
        ? globalThis.String(object.sender_name)
        : undefined,
      senderAddress: isSet(object.senderAddress)
        ? globalThis.String(object.senderAddress)
        : isSet(object.sender_address)
        ? globalThis.String(object.sender_address)
        : undefined,
      userVerificationTemplate: isSet(object.userVerificationTemplate)
        ? EmailTemplate.fromJSON(object.userVerificationTemplate)
        : isSet(object.user_verification_template)
        ? EmailTemplate.fromJSON(object.user_verification_template)
        : undefined,
      passwordResetTemplate: isSet(object.passwordResetTemplate)
        ? EmailTemplate.fromJSON(object.passwordResetTemplate)
        : isSet(object.password_reset_template)
        ? EmailTemplate.fromJSON(object.password_reset_template)
        : undefined,
      changeEmailTemplate: isSet(object.changeEmailTemplate)
        ? EmailTemplate.fromJSON(object.changeEmailTemplate)
        : isSet(object.change_email_template)
        ? EmailTemplate.fromJSON(object.change_email_template)
        : undefined,
      otpTemplate: isSet(object.otpTemplate)
        ? EmailTemplate.fromJSON(object.otpTemplate)
        : isSet(object.otp_template)
        ? EmailTemplate.fromJSON(object.otp_template)
        : undefined,
    };
  },

  toJSON(message: EmailConfig): unknown {
    const obj: any = {};
    if (message.smtpHost !== undefined && message.smtpHost !== "") {
      obj.smtpHost = message.smtpHost;
    }
    if (message.smtpPort !== undefined && message.smtpPort !== 0) {
      obj.smtpPort = Math.round(message.smtpPort);
    }
    if (message.smtpUsername !== undefined && message.smtpUsername !== "") {
      obj.smtpUsername = message.smtpUsername;
    }
    if (message.smtpPassword !== undefined && message.smtpPassword !== "") {
      obj.smtpPassword = message.smtpPassword;
    }
    if (message.smtpEncryption !== undefined && message.smtpEncryption !== 0) {
      obj.smtpEncryption = smtpEncryptionToJSON(message.smtpEncryption);
    }
    if (message.senderName !== undefined && message.senderName !== "") {
      obj.senderName = message.senderName;
    }
    if (message.senderAddress !== undefined && message.senderAddress !== "") {
      obj.senderAddress = message.senderAddress;
    }
    if (message.userVerificationTemplate !== undefined) {
      obj.userVerificationTemplate = EmailTemplate.toJSON(message.userVerificationTemplate);
    }
    if (message.passwordResetTemplate !== undefined) {
      obj.passwordResetTemplate = EmailTemplate.toJSON(message.passwordResetTemplate);
    }
    if (message.changeEmailTemplate !== undefined) {
      obj.changeEmailTemplate = EmailTemplate.toJSON(message.changeEmailTemplate);
    }
    if (message.otpTemplate !== undefined) {
      obj.otpTemplate = EmailTemplate.toJSON(message.otpTemplate);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmailConfig>, I>>(base?: I): EmailConfig {
    return EmailConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmailConfig>, I>>(object: I): EmailConfig {
    const message = createBaseEmailConfig();
    message.smtpHost = object.smtpHost ?? "";
    message.smtpPort = object.smtpPort ?? 0;
    message.smtpUsername = object.smtpUsername ?? "";
    message.smtpPassword = object.smtpPassword ?? "";
    message.smtpEncryption = object.smtpEncryption ?? 0;
    message.senderName = object.senderName ?? "";
    message.senderAddress = object.senderAddress ?? "";
    message.userVerificationTemplate =
      (object.userVerificationTemplate !== undefined && object.userVerificationTemplate !== null)
        ? EmailTemplate.fromPartial(object.userVerificationTemplate)
        : undefined;
    message.passwordResetTemplate =
      (object.passwordResetTemplate !== undefined && object.passwordResetTemplate !== null)
        ? EmailTemplate.fromPartial(object.passwordResetTemplate)
        : undefined;
    message.changeEmailTemplate = (object.changeEmailTemplate !== undefined && object.changeEmailTemplate !== null)
      ? EmailTemplate.fromPartial(object.changeEmailTemplate)
      : undefined;
    message.otpTemplate = (object.otpTemplate !== undefined && object.otpTemplate !== null)
      ? EmailTemplate.fromPartial(object.otpTemplate)
      : undefined;
    return message;
  },
};

function createBaseOAuthProviderConfig(): OAuthProviderConfig {
  return {};
}

export const OAuthProviderConfig: MessageFns<OAuthProviderConfig> = {
  encode(message: OAuthProviderConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientId !== undefined && message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    if (message.clientSecret !== undefined && message.clientSecret !== "") {
      writer.uint32(18).string(message.clientSecret);
    }
    if (message.providerId !== undefined && message.providerId !== 0) {
      writer.uint32(24).int32(message.providerId);
    }
    if (message.displayName !== undefined && message.displayName !== "") {
      writer.uint32(90).string(message.displayName);
    }
    if (message.authUrl !== undefined && message.authUrl !== "") {
      writer.uint32(98).string(message.authUrl);
    }
    if (message.tokenUrl !== undefined && message.tokenUrl !== "") {
      writer.uint32(106).string(message.tokenUrl);
    }
    if (message.userApiUrl !== undefined && message.userApiUrl !== "") {
      writer.uint32(114).string(message.userApiUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OAuthProviderConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOAuthProviderConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientSecret = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.providerId = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.authUrl = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.tokenUrl = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.userApiUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OAuthProviderConfig {
    return {
      clientId: isSet(object.clientId)
        ? globalThis.String(object.clientId)
        : isSet(object.client_id)
        ? globalThis.String(object.client_id)
        : undefined,
      clientSecret: isSet(object.clientSecret)
        ? globalThis.String(object.clientSecret)
        : isSet(object.client_secret)
        ? globalThis.String(object.client_secret)
        : undefined,
      providerId: isSet(object.providerId)
        ? oAuthProviderIdFromJSON(object.providerId)
        : isSet(object.provider_id)
        ? oAuthProviderIdFromJSON(object.provider_id)
        : undefined,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : undefined,
      authUrl: isSet(object.authUrl)
        ? globalThis.String(object.authUrl)
        : isSet(object.auth_url)
        ? globalThis.String(object.auth_url)
        : undefined,
      tokenUrl: isSet(object.tokenUrl)
        ? globalThis.String(object.tokenUrl)
        : isSet(object.token_url)
        ? globalThis.String(object.token_url)
        : undefined,
      userApiUrl: isSet(object.userApiUrl)
        ? globalThis.String(object.userApiUrl)
        : isSet(object.user_api_url)
        ? globalThis.String(object.user_api_url)
        : undefined,
    };
  },

  toJSON(message: OAuthProviderConfig): unknown {
    const obj: any = {};
    if (message.clientId !== undefined && message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.clientSecret !== undefined && message.clientSecret !== "") {
      obj.clientSecret = message.clientSecret;
    }
    if (message.providerId !== undefined && message.providerId !== 0) {
      obj.providerId = oAuthProviderIdToJSON(message.providerId);
    }
    if (message.displayName !== undefined && message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.authUrl !== undefined && message.authUrl !== "") {
      obj.authUrl = message.authUrl;
    }
    if (message.tokenUrl !== undefined && message.tokenUrl !== "") {
      obj.tokenUrl = message.tokenUrl;
    }
    if (message.userApiUrl !== undefined && message.userApiUrl !== "") {
      obj.userApiUrl = message.userApiUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OAuthProviderConfig>, I>>(base?: I): OAuthProviderConfig {
    return OAuthProviderConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OAuthProviderConfig>, I>>(object: I): OAuthProviderConfig {
    const message = createBaseOAuthProviderConfig();
    message.clientId = object.clientId ?? "";
    message.clientSecret = object.clientSecret ?? "";
    message.providerId = object.providerId ?? 0;
    message.displayName = object.displayName ?? "";
    message.authUrl = object.authUrl ?? "";
    message.tokenUrl = object.tokenUrl ?? "";
    message.userApiUrl = object.userApiUrl ?? "";
    return message;
  },
};

function createBaseAuthConfig(): AuthConfig {
  return { oauthProviders: {}, customUriSchemes: [], redirectUriAllowlist: [] };
}

export const AuthConfig: MessageFns<AuthConfig> = {
  encode(message: AuthConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authTokenTtlSec !== undefined && message.authTokenTtlSec !== 0n) {
      if (BigInt.asIntN(64, message.authTokenTtlSec) !== message.authTokenTtlSec) {
        throw new globalThis.Error("value provided for field message.authTokenTtlSec of type int64 too large");
      }
      writer.uint32(8).int64(message.authTokenTtlSec);
    }
    if (message.refreshTokenTtlSec !== undefined && message.refreshTokenTtlSec !== 0n) {
      if (BigInt.asIntN(64, message.refreshTokenTtlSec) !== message.refreshTokenTtlSec) {
        throw new globalThis.Error("value provided for field message.refreshTokenTtlSec of type int64 too large");
      }
      writer.uint32(16).int64(message.refreshTokenTtlSec);
    }
    if (message.disablePasswordAuth !== undefined && message.disablePasswordAuth !== false) {
      writer.uint32(24).bool(message.disablePasswordAuth);
    }
    if (message.enableOtpSignin !== undefined && message.enableOtpSignin !== false) {
      writer.uint32(64).bool(message.enableOtpSignin);
    }
    if (message.enableAnonymousSignin !== undefined && message.enableAnonymousSignin !== false) {
      writer.uint32(96).bool(message.enableAnonymousSignin);
    }
    if (message.passwordMinimalLength !== undefined && message.passwordMinimalLength !== 0) {
      writer.uint32(32).uint32(message.passwordMinimalLength);
    }
    if (
      message.passwordMustContainUpperAndLowerCase !== undefined &&
      message.passwordMustContainUpperAndLowerCase !== false
    ) {
      writer.uint32(40).bool(message.passwordMustContainUpperAndLowerCase);
    }
    if (message.passwordMustContainDigits !== undefined && message.passwordMustContainDigits !== false) {
      writer.uint32(48).bool(message.passwordMustContainDigits);
    }
    if (
      message.passwordMustContainSpecialCharacters !== undefined &&
      message.passwordMustContainSpecialCharacters !== false
    ) {
      writer.uint32(56).bool(message.passwordMustContainSpecialCharacters);
    }
    globalThis.Object.entries(message.oauthProviders).forEach(([key, value]: [string, OAuthProviderConfig]) => {
      AuthConfig_OauthProvidersEntry.encode({ key: key as any, value }, writer.uint32(90).fork()).join();
    });
    for (const v of message.customUriSchemes) {
      writer.uint32(170).string(v!);
    }
    for (const v of message.redirectUriAllowlist) {
      writer.uint32(178).string(v!);
    }
    if (message.userIdentifier !== undefined && message.userIdentifier !== 0) {
      writer.uint32(248).int32(message.userIdentifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.authTokenTtlSec = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.refreshTokenTtlSec = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.disablePasswordAuth = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.enableOtpSignin = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.enableAnonymousSignin = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.passwordMinimalLength = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.passwordMustContainUpperAndLowerCase = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.passwordMustContainDigits = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.passwordMustContainSpecialCharacters = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          const entry11 = AuthConfig_OauthProvidersEntry.decode(reader, reader.uint32());
          if (entry11.value !== undefined) {
            message.oauthProviders[entry11.key] = entry11.value;
          }
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.customUriSchemes.push(reader.string());
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.redirectUriAllowlist.push(reader.string());
          continue;
        }
        case 31: {
          if (tag !== 248) {
            break;
          }

          message.userIdentifier = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthConfig {
    return {
      authTokenTtlSec: isSet(object.authTokenTtlSec)
        ? BigInt(object.authTokenTtlSec)
        : isSet(object.auth_token_ttl_sec)
        ? BigInt(object.auth_token_ttl_sec)
        : undefined,
      refreshTokenTtlSec: isSet(object.refreshTokenTtlSec)
        ? BigInt(object.refreshTokenTtlSec)
        : isSet(object.refresh_token_ttl_sec)
        ? BigInt(object.refresh_token_ttl_sec)
        : undefined,
      disablePasswordAuth: isSet(object.disablePasswordAuth)
        ? globalThis.Boolean(object.disablePasswordAuth)
        : isSet(object.disable_password_auth)
        ? globalThis.Boolean(object.disable_password_auth)
        : undefined,
      enableOtpSignin: isSet(object.enableOtpSignin)
        ? globalThis.Boolean(object.enableOtpSignin)
        : isSet(object.enable_otp_signin)
        ? globalThis.Boolean(object.enable_otp_signin)
        : undefined,
      enableAnonymousSignin: isSet(object.enableAnonymousSignin)
        ? globalThis.Boolean(object.enableAnonymousSignin)
        : isSet(object.enable_anonymous_signin)
        ? globalThis.Boolean(object.enable_anonymous_signin)
        : undefined,
      passwordMinimalLength: isSet(object.passwordMinimalLength)
        ? globalThis.Number(object.passwordMinimalLength)
        : isSet(object.password_minimal_length)
        ? globalThis.Number(object.password_minimal_length)
        : undefined,
      passwordMustContainUpperAndLowerCase: isSet(object.passwordMustContainUpperAndLowerCase)
        ? globalThis.Boolean(object.passwordMustContainUpperAndLowerCase)
        : isSet(object.password_must_contain_upper_and_lower_case)
        ? globalThis.Boolean(object.password_must_contain_upper_and_lower_case)
        : undefined,
      passwordMustContainDigits: isSet(object.passwordMustContainDigits)
        ? globalThis.Boolean(object.passwordMustContainDigits)
        : isSet(object.password_must_contain_digits)
        ? globalThis.Boolean(object.password_must_contain_digits)
        : undefined,
      passwordMustContainSpecialCharacters: isSet(object.passwordMustContainSpecialCharacters)
        ? globalThis.Boolean(object.passwordMustContainSpecialCharacters)
        : isSet(object.password_must_contain_special_characters)
        ? globalThis.Boolean(object.password_must_contain_special_characters)
        : undefined,
      oauthProviders: isObject(object.oauthProviders)
        ? (globalThis.Object.entries(object.oauthProviders) as [string, any][]).reduce(
          (acc: { [key: string]: OAuthProviderConfig }, [key, value]: [string, any]) => {
            acc[key] = OAuthProviderConfig.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.oauth_providers)
        ? (globalThis.Object.entries(object.oauth_providers) as [string, any][]).reduce(
          (acc: { [key: string]: OAuthProviderConfig }, [key, value]: [string, any]) => {
            acc[key] = OAuthProviderConfig.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      customUriSchemes: globalThis.Array.isArray(object?.customUriSchemes)
        ? object.customUriSchemes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.custom_uri_schemes)
        ? object.custom_uri_schemes.map((e: any) => globalThis.String(e))
        : [],
      redirectUriAllowlist: globalThis.Array.isArray(object?.redirectUriAllowlist)
        ? object.redirectUriAllowlist.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.redirect_uri_allowlist)
        ? object.redirect_uri_allowlist.map((e: any) => globalThis.String(e))
        : [],
      userIdentifier: isSet(object.userIdentifier)
        ? userIdentifierFromJSON(object.userIdentifier)
        : isSet(object.user_identifier)
        ? userIdentifierFromJSON(object.user_identifier)
        : undefined,
    };
  },

  toJSON(message: AuthConfig): unknown {
    const obj: any = {};
    if (message.authTokenTtlSec !== undefined && message.authTokenTtlSec !== 0n) {
      obj.authTokenTtlSec = message.authTokenTtlSec.toString();
    }
    if (message.refreshTokenTtlSec !== undefined && message.refreshTokenTtlSec !== 0n) {
      obj.refreshTokenTtlSec = message.refreshTokenTtlSec.toString();
    }
    if (message.disablePasswordAuth !== undefined && message.disablePasswordAuth !== false) {
      obj.disablePasswordAuth = message.disablePasswordAuth;
    }
    if (message.enableOtpSignin !== undefined && message.enableOtpSignin !== false) {
      obj.enableOtpSignin = message.enableOtpSignin;
    }
    if (message.enableAnonymousSignin !== undefined && message.enableAnonymousSignin !== false) {
      obj.enableAnonymousSignin = message.enableAnonymousSignin;
    }
    if (message.passwordMinimalLength !== undefined && message.passwordMinimalLength !== 0) {
      obj.passwordMinimalLength = Math.round(message.passwordMinimalLength);
    }
    if (
      message.passwordMustContainUpperAndLowerCase !== undefined &&
      message.passwordMustContainUpperAndLowerCase !== false
    ) {
      obj.passwordMustContainUpperAndLowerCase = message.passwordMustContainUpperAndLowerCase;
    }
    if (message.passwordMustContainDigits !== undefined && message.passwordMustContainDigits !== false) {
      obj.passwordMustContainDigits = message.passwordMustContainDigits;
    }
    if (
      message.passwordMustContainSpecialCharacters !== undefined &&
      message.passwordMustContainSpecialCharacters !== false
    ) {
      obj.passwordMustContainSpecialCharacters = message.passwordMustContainSpecialCharacters;
    }
    if (message.oauthProviders) {
      const entries = globalThis.Object.entries(message.oauthProviders) as [string, OAuthProviderConfig][];
      if (entries.length > 0) {
        obj.oauthProviders = {};
        entries.forEach(([k, v]) => {
          obj.oauthProviders[k] = OAuthProviderConfig.toJSON(v);
        });
      }
    }
    if (message.customUriSchemes?.length) {
      obj.customUriSchemes = message.customUriSchemes;
    }
    if (message.redirectUriAllowlist?.length) {
      obj.redirectUriAllowlist = message.redirectUriAllowlist;
    }
    if (message.userIdentifier !== undefined && message.userIdentifier !== 0) {
      obj.userIdentifier = userIdentifierToJSON(message.userIdentifier);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthConfig>, I>>(base?: I): AuthConfig {
    return AuthConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthConfig>, I>>(object: I): AuthConfig {
    const message = createBaseAuthConfig();
    message.authTokenTtlSec = object.authTokenTtlSec ?? 0n;
    message.refreshTokenTtlSec = object.refreshTokenTtlSec ?? 0n;
    message.disablePasswordAuth = object.disablePasswordAuth ?? false;
    message.enableOtpSignin = object.enableOtpSignin ?? false;
    message.enableAnonymousSignin = object.enableAnonymousSignin ?? false;
    message.passwordMinimalLength = object.passwordMinimalLength ?? 0;
    message.passwordMustContainUpperAndLowerCase = object.passwordMustContainUpperAndLowerCase ?? false;
    message.passwordMustContainDigits = object.passwordMustContainDigits ?? false;
    message.passwordMustContainSpecialCharacters = object.passwordMustContainSpecialCharacters ?? false;
    message.oauthProviders = (globalThis.Object.entries(object.oauthProviders ?? {}) as [string, OAuthProviderConfig][])
      .reduce((acc: { [key: string]: OAuthProviderConfig }, [key, value]: [string, OAuthProviderConfig]) => {
        if (value !== undefined) {
          acc[key] = OAuthProviderConfig.fromPartial(value);
        }
        return acc;
      }, {});
    message.customUriSchemes = object.customUriSchemes?.map((e) => e) || [];
    message.redirectUriAllowlist = object.redirectUriAllowlist?.map((e) => e) || [];
    message.userIdentifier = object.userIdentifier ?? 0;
    return message;
  },
};

function createBaseAuthConfig_OauthProvidersEntry(): AuthConfig_OauthProvidersEntry {
  return { key: "", value: undefined };
}

export const AuthConfig_OauthProvidersEntry: MessageFns<AuthConfig_OauthProvidersEntry> = {
  encode(message: AuthConfig_OauthProvidersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      OAuthProviderConfig.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthConfig_OauthProvidersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthConfig_OauthProvidersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = OAuthProviderConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthConfig_OauthProvidersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? OAuthProviderConfig.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: AuthConfig_OauthProvidersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = OAuthProviderConfig.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthConfig_OauthProvidersEntry>, I>>(base?: I): AuthConfig_OauthProvidersEntry {
    return AuthConfig_OauthProvidersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthConfig_OauthProvidersEntry>, I>>(
    object: I,
  ): AuthConfig_OauthProvidersEntry {
    const message = createBaseAuthConfig_OauthProvidersEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? OAuthProviderConfig.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseS3StorageConfig(): S3StorageConfig {
  return {};
}

export const S3StorageConfig: MessageFns<S3StorageConfig> = {
  encode(message: S3StorageConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.endpoint !== undefined && message.endpoint !== "") {
      writer.uint32(10).string(message.endpoint);
    }
    if (message.region !== undefined && message.region !== "") {
      writer.uint32(18).string(message.region);
    }
    if (message.bucketName !== undefined && message.bucketName !== "") {
      writer.uint32(42).string(message.bucketName);
    }
    if (message.accessKey !== undefined && message.accessKey !== "") {
      writer.uint32(66).string(message.accessKey);
    }
    if (message.secretAccessKey !== undefined && message.secretAccessKey !== "") {
      writer.uint32(74).string(message.secretAccessKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S3StorageConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS3StorageConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.endpoint = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.region = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.bucketName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.accessKey = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.secretAccessKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): S3StorageConfig {
    return {
      endpoint: isSet(object.endpoint) ? globalThis.String(object.endpoint) : undefined,
      region: isSet(object.region) ? globalThis.String(object.region) : undefined,
      bucketName: isSet(object.bucketName)
        ? globalThis.String(object.bucketName)
        : isSet(object.bucket_name)
        ? globalThis.String(object.bucket_name)
        : undefined,
      accessKey: isSet(object.accessKey)
        ? globalThis.String(object.accessKey)
        : isSet(object.access_key)
        ? globalThis.String(object.access_key)
        : undefined,
      secretAccessKey: isSet(object.secretAccessKey)
        ? globalThis.String(object.secretAccessKey)
        : isSet(object.secret_access_key)
        ? globalThis.String(object.secret_access_key)
        : undefined,
    };
  },

  toJSON(message: S3StorageConfig): unknown {
    const obj: any = {};
    if (message.endpoint !== undefined && message.endpoint !== "") {
      obj.endpoint = message.endpoint;
    }
    if (message.region !== undefined && message.region !== "") {
      obj.region = message.region;
    }
    if (message.bucketName !== undefined && message.bucketName !== "") {
      obj.bucketName = message.bucketName;
    }
    if (message.accessKey !== undefined && message.accessKey !== "") {
      obj.accessKey = message.accessKey;
    }
    if (message.secretAccessKey !== undefined && message.secretAccessKey !== "") {
      obj.secretAccessKey = message.secretAccessKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<S3StorageConfig>, I>>(base?: I): S3StorageConfig {
    return S3StorageConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S3StorageConfig>, I>>(object: I): S3StorageConfig {
    const message = createBaseS3StorageConfig();
    message.endpoint = object.endpoint ?? "";
    message.region = object.region ?? "";
    message.bucketName = object.bucketName ?? "";
    message.accessKey = object.accessKey ?? "";
    message.secretAccessKey = object.secretAccessKey ?? "";
    return message;
  },
};

function createBaseServerConfig(): ServerConfig {
  return {};
}

export const ServerConfig: MessageFns<ServerConfig> = {
  encode(message: ServerConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.applicationName !== undefined && message.applicationName !== "") {
      writer.uint32(10).string(message.applicationName);
    }
    if (message.siteUrl !== undefined && message.siteUrl !== "") {
      writer.uint32(18).string(message.siteUrl);
    }
    if (message.logsRetentionSec !== undefined && message.logsRetentionSec !== 0n) {
      if (BigInt.asIntN(64, message.logsRetentionSec) !== message.logsRetentionSec) {
        throw new globalThis.Error("value provided for field message.logsRetentionSec of type int64 too large");
      }
      writer.uint32(88).int64(message.logsRetentionSec);
    }
    if (message.s3StorageConfig !== undefined) {
      S3StorageConfig.encode(message.s3StorageConfig, writer.uint32(106).fork()).join();
    }
    if (message.enableRecordTransactions !== undefined && message.enableRecordTransactions !== false) {
      writer.uint32(112).bool(message.enableRecordTransactions);
    }
    if (message.requestSizeLimitBytes !== undefined && message.requestSizeLimitBytes !== 0n) {
      if (BigInt.asUintN(64, message.requestSizeLimitBytes) !== message.requestSizeLimitBytes) {
        throw new globalThis.Error("value provided for field message.requestSizeLimitBytes of type uint64 too large");
      }
      writer.uint32(120).uint64(message.requestSizeLimitBytes);
    }
    if (message.authIpRateLimit !== undefined && message.authIpRateLimit !== 0) {
      writer.uint32(128).uint32(message.authIpRateLimit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.applicationName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.siteUrl = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.logsRetentionSec = reader.int64() as bigint;
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.s3StorageConfig = S3StorageConfig.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.enableRecordTransactions = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.requestSizeLimitBytes = reader.uint64() as bigint;
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.authIpRateLimit = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerConfig {
    return {
      applicationName: isSet(object.applicationName)
        ? globalThis.String(object.applicationName)
        : isSet(object.application_name)
        ? globalThis.String(object.application_name)
        : undefined,
      siteUrl: isSet(object.siteUrl)
        ? globalThis.String(object.siteUrl)
        : isSet(object.site_url)
        ? globalThis.String(object.site_url)
        : undefined,
      logsRetentionSec: isSet(object.logsRetentionSec)
        ? BigInt(object.logsRetentionSec)
        : isSet(object.logs_retention_sec)
        ? BigInt(object.logs_retention_sec)
        : undefined,
      s3StorageConfig: isSet(object.s3StorageConfig)
        ? S3StorageConfig.fromJSON(object.s3StorageConfig)
        : isSet(object.s3_storage_config)
        ? S3StorageConfig.fromJSON(object.s3_storage_config)
        : undefined,
      enableRecordTransactions: isSet(object.enableRecordTransactions)
        ? globalThis.Boolean(object.enableRecordTransactions)
        : isSet(object.enable_record_transactions)
        ? globalThis.Boolean(object.enable_record_transactions)
        : undefined,
      requestSizeLimitBytes: isSet(object.requestSizeLimitBytes)
        ? BigInt(object.requestSizeLimitBytes)
        : isSet(object.request_size_limit_bytes)
        ? BigInt(object.request_size_limit_bytes)
        : undefined,
      authIpRateLimit: isSet(object.authIpRateLimit)
        ? globalThis.Number(object.authIpRateLimit)
        : isSet(object.auth_ip_rate_limit)
        ? globalThis.Number(object.auth_ip_rate_limit)
        : undefined,
    };
  },

  toJSON(message: ServerConfig): unknown {
    const obj: any = {};
    if (message.applicationName !== undefined && message.applicationName !== "") {
      obj.applicationName = message.applicationName;
    }
    if (message.siteUrl !== undefined && message.siteUrl !== "") {
      obj.siteUrl = message.siteUrl;
    }
    if (message.logsRetentionSec !== undefined && message.logsRetentionSec !== 0n) {
      obj.logsRetentionSec = message.logsRetentionSec.toString();
    }
    if (message.s3StorageConfig !== undefined) {
      obj.s3StorageConfig = S3StorageConfig.toJSON(message.s3StorageConfig);
    }
    if (message.enableRecordTransactions !== undefined && message.enableRecordTransactions !== false) {
      obj.enableRecordTransactions = message.enableRecordTransactions;
    }
    if (message.requestSizeLimitBytes !== undefined && message.requestSizeLimitBytes !== 0n) {
      obj.requestSizeLimitBytes = message.requestSizeLimitBytes.toString();
    }
    if (message.authIpRateLimit !== undefined && message.authIpRateLimit !== 0) {
      obj.authIpRateLimit = Math.round(message.authIpRateLimit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerConfig>, I>>(base?: I): ServerConfig {
    return ServerConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerConfig>, I>>(object: I): ServerConfig {
    const message = createBaseServerConfig();
    message.applicationName = object.applicationName ?? "";
    message.siteUrl = object.siteUrl ?? "";
    message.logsRetentionSec = object.logsRetentionSec ?? 0n;
    message.s3StorageConfig = (object.s3StorageConfig !== undefined && object.s3StorageConfig !== null)
      ? S3StorageConfig.fromPartial(object.s3StorageConfig)
      : undefined;
    message.enableRecordTransactions = object.enableRecordTransactions ?? false;
    message.requestSizeLimitBytes = object.requestSizeLimitBytes ?? 0n;
    message.authIpRateLimit = object.authIpRateLimit ?? 0;
    return message;
  },
};

function createBaseSystemJob(): SystemJob {
  return {};
}

export const SystemJob: MessageFns<SystemJob> = {
  encode(message: SystemJob, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.schedule !== undefined && message.schedule !== "") {
      writer.uint32(18).string(message.schedule);
    }
    if (message.disabled !== undefined && message.disabled !== false) {
      writer.uint32(24).bool(message.disabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SystemJob {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSystemJob();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.schedule = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.disabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SystemJob {
    return {
      id: isSet(object.id) ? systemJobIdFromJSON(object.id) : undefined,
      schedule: isSet(object.schedule) ? globalThis.String(object.schedule) : undefined,
      disabled: isSet(object.disabled) ? globalThis.Boolean(object.disabled) : undefined,
    };
  },

  toJSON(message: SystemJob): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== 0) {
      obj.id = systemJobIdToJSON(message.id);
    }
    if (message.schedule !== undefined && message.schedule !== "") {
      obj.schedule = message.schedule;
    }
    if (message.disabled !== undefined && message.disabled !== false) {
      obj.disabled = message.disabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SystemJob>, I>>(base?: I): SystemJob {
    return SystemJob.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SystemJob>, I>>(object: I): SystemJob {
    const message = createBaseSystemJob();
    message.id = object.id ?? 0;
    message.schedule = object.schedule ?? "";
    message.disabled = object.disabled ?? false;
    return message;
  },
};

function createBaseJobsConfig(): JobsConfig {
  return { systemJobs: [] };
}

export const JobsConfig: MessageFns<JobsConfig> = {
  encode(message: JobsConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.systemJobs) {
      SystemJob.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobsConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobsConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.systemJobs.push(SystemJob.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobsConfig {
    return {
      systemJobs: globalThis.Array.isArray(object?.systemJobs)
        ? object.systemJobs.map((e: any) => SystemJob.fromJSON(e))
        : globalThis.Array.isArray(object?.system_jobs)
        ? object.system_jobs.map((e: any) => SystemJob.fromJSON(e))
        : [],
    };
  },

  toJSON(message: JobsConfig): unknown {
    const obj: any = {};
    if (message.systemJobs?.length) {
      obj.systemJobs = message.systemJobs.map((e) => SystemJob.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobsConfig>, I>>(base?: I): JobsConfig {
    return JobsConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobsConfig>, I>>(object: I): JobsConfig {
    const message = createBaseJobsConfig();
    message.systemJobs = object.systemJobs?.map((e) => SystemJob.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRecordApiConfig(): RecordApiConfig {
  return { attachedDatabases: [], aclWorld: [], aclAuthenticated: [], excludedColumns: [], expand: [] };
}

export const RecordApiConfig: MessageFns<RecordApiConfig> = {
  encode(message: RecordApiConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined && message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.tableName !== undefined && message.tableName !== "") {
      writer.uint32(18).string(message.tableName);
    }
    for (const v of message.attachedDatabases) {
      writer.uint32(26).string(v!);
    }
    if (message.conflictResolution !== undefined && message.conflictResolution !== 0) {
      writer.uint32(40).int32(message.conflictResolution);
    }
    if (message.autofillMissingUserIdColumns !== undefined && message.autofillMissingUserIdColumns !== false) {
      writer.uint32(48).bool(message.autofillMissingUserIdColumns);
    }
    if (message.enableSubscriptions !== undefined && message.enableSubscriptions !== false) {
      writer.uint32(72).bool(message.enableSubscriptions);
    }
    for (const v of message.aclWorld) {
      writer.uint32(56).int32(v!);
    }
    for (const v of message.aclAuthenticated) {
      writer.uint32(64).int32(v!);
    }
    for (const v of message.excludedColumns) {
      writer.uint32(82).string(v!);
    }
    if (message.createAccessRule !== undefined && message.createAccessRule !== "") {
      writer.uint32(90).string(message.createAccessRule);
    }
    if (message.readAccessRule !== undefined && message.readAccessRule !== "") {
      writer.uint32(98).string(message.readAccessRule);
    }
    if (message.updateAccessRule !== undefined && message.updateAccessRule !== "") {
      writer.uint32(106).string(message.updateAccessRule);
    }
    if (message.deleteAccessRule !== undefined && message.deleteAccessRule !== "") {
      writer.uint32(114).string(message.deleteAccessRule);
    }
    if (message.schemaAccessRule !== undefined && message.schemaAccessRule !== "") {
      writer.uint32(122).string(message.schemaAccessRule);
    }
    for (const v of message.expand) {
      writer.uint32(170).string(v!);
    }
    if (message.listingHardLimit !== undefined && message.listingHardLimit !== 0n) {
      if (BigInt.asUintN(64, message.listingHardLimit) !== message.listingHardLimit) {
        throw new globalThis.Error("value provided for field message.listingHardLimit of type uint64 too large");
      }
      writer.uint32(176).uint64(message.listingHardLimit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordApiConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordApiConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tableName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.attachedDatabases.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.conflictResolution = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.autofillMissingUserIdColumns = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.enableSubscriptions = reader.bool();
          continue;
        }
        case 7: {
          if (tag === 56) {
            message.aclWorld.push(reader.int32() as any);

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.aclWorld.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 8: {
          if (tag === 64) {
            message.aclAuthenticated.push(reader.int32() as any);

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.aclAuthenticated.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.excludedColumns.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.createAccessRule = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.readAccessRule = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.updateAccessRule = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.deleteAccessRule = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.schemaAccessRule = reader.string();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.expand.push(reader.string());
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.listingHardLimit = reader.uint64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordApiConfig {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      tableName: isSet(object.tableName)
        ? globalThis.String(object.tableName)
        : isSet(object.table_name)
        ? globalThis.String(object.table_name)
        : undefined,
      attachedDatabases: globalThis.Array.isArray(object?.attachedDatabases)
        ? object.attachedDatabases.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.attached_databases)
        ? object.attached_databases.map((e: any) => globalThis.String(e))
        : [],
      conflictResolution: isSet(object.conflictResolution)
        ? conflictResolutionStrategyFromJSON(object.conflictResolution)
        : isSet(object.conflict_resolution)
        ? conflictResolutionStrategyFromJSON(object.conflict_resolution)
        : undefined,
      autofillMissingUserIdColumns: isSet(object.autofillMissingUserIdColumns)
        ? globalThis.Boolean(object.autofillMissingUserIdColumns)
        : isSet(object.autofill_missing_user_id_columns)
        ? globalThis.Boolean(object.autofill_missing_user_id_columns)
        : undefined,
      enableSubscriptions: isSet(object.enableSubscriptions)
        ? globalThis.Boolean(object.enableSubscriptions)
        : isSet(object.enable_subscriptions)
        ? globalThis.Boolean(object.enable_subscriptions)
        : undefined,
      aclWorld: globalThis.Array.isArray(object?.aclWorld)
        ? object.aclWorld.map((e: any) => permissionFlagFromJSON(e))
        : globalThis.Array.isArray(object?.acl_world)
        ? object.acl_world.map((e: any) => permissionFlagFromJSON(e))
        : [],
      aclAuthenticated: globalThis.Array.isArray(object?.aclAuthenticated)
        ? object.aclAuthenticated.map((e: any) => permissionFlagFromJSON(e))
        : globalThis.Array.isArray(object?.acl_authenticated)
        ? object.acl_authenticated.map((e: any) => permissionFlagFromJSON(e))
        : [],
      excludedColumns: globalThis.Array.isArray(object?.excludedColumns)
        ? object.excludedColumns.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.excluded_columns)
        ? object.excluded_columns.map((e: any) => globalThis.String(e))
        : [],
      createAccessRule: isSet(object.createAccessRule)
        ? globalThis.String(object.createAccessRule)
        : isSet(object.create_access_rule)
        ? globalThis.String(object.create_access_rule)
        : undefined,
      readAccessRule: isSet(object.readAccessRule)
        ? globalThis.String(object.readAccessRule)
        : isSet(object.read_access_rule)
        ? globalThis.String(object.read_access_rule)
        : undefined,
      updateAccessRule: isSet(object.updateAccessRule)
        ? globalThis.String(object.updateAccessRule)
        : isSet(object.update_access_rule)
        ? globalThis.String(object.update_access_rule)
        : undefined,
      deleteAccessRule: isSet(object.deleteAccessRule)
        ? globalThis.String(object.deleteAccessRule)
        : isSet(object.delete_access_rule)
        ? globalThis.String(object.delete_access_rule)
        : undefined,
      schemaAccessRule: isSet(object.schemaAccessRule)
        ? globalThis.String(object.schemaAccessRule)
        : isSet(object.schema_access_rule)
        ? globalThis.String(object.schema_access_rule)
        : undefined,
      expand: globalThis.Array.isArray(object?.expand)
        ? object.expand.map((e: any) => globalThis.String(e))
        : [],
      listingHardLimit: isSet(object.listingHardLimit)
        ? BigInt(object.listingHardLimit)
        : isSet(object.listing_hard_limit)
        ? BigInt(object.listing_hard_limit)
        : undefined,
    };
  },

  toJSON(message: RecordApiConfig): unknown {
    const obj: any = {};
    if (message.name !== undefined && message.name !== "") {
      obj.name = message.name;
    }
    if (message.tableName !== undefined && message.tableName !== "") {
      obj.tableName = message.tableName;
    }
    if (message.attachedDatabases?.length) {
      obj.attachedDatabases = message.attachedDatabases;
    }
    if (message.conflictResolution !== undefined && message.conflictResolution !== 0) {
      obj.conflictResolution = conflictResolutionStrategyToJSON(message.conflictResolution);
    }
    if (message.autofillMissingUserIdColumns !== undefined && message.autofillMissingUserIdColumns !== false) {
      obj.autofillMissingUserIdColumns = message.autofillMissingUserIdColumns;
    }
    if (message.enableSubscriptions !== undefined && message.enableSubscriptions !== false) {
      obj.enableSubscriptions = message.enableSubscriptions;
    }
    if (message.aclWorld?.length) {
      obj.aclWorld = message.aclWorld.map((e) => permissionFlagToJSON(e));
    }
    if (message.aclAuthenticated?.length) {
      obj.aclAuthenticated = message.aclAuthenticated.map((e) => permissionFlagToJSON(e));
    }
    if (message.excludedColumns?.length) {
      obj.excludedColumns = message.excludedColumns;
    }
    if (message.createAccessRule !== undefined && message.createAccessRule !== "") {
      obj.createAccessRule = message.createAccessRule;
    }
    if (message.readAccessRule !== undefined && message.readAccessRule !== "") {
      obj.readAccessRule = message.readAccessRule;
    }
    if (message.updateAccessRule !== undefined && message.updateAccessRule !== "") {
      obj.updateAccessRule = message.updateAccessRule;
    }
    if (message.deleteAccessRule !== undefined && message.deleteAccessRule !== "") {
      obj.deleteAccessRule = message.deleteAccessRule;
    }
    if (message.schemaAccessRule !== undefined && message.schemaAccessRule !== "") {
      obj.schemaAccessRule = message.schemaAccessRule;
    }
    if (message.expand?.length) {
      obj.expand = message.expand;
    }
    if (message.listingHardLimit !== undefined && message.listingHardLimit !== 0n) {
      obj.listingHardLimit = message.listingHardLimit.toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordApiConfig>, I>>(base?: I): RecordApiConfig {
    return RecordApiConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordApiConfig>, I>>(object: I): RecordApiConfig {
    const message = createBaseRecordApiConfig();
    message.name = object.name ?? "";
    message.tableName = object.tableName ?? "";
    message.attachedDatabases = object.attachedDatabases?.map((e) => e) || [];
    message.conflictResolution = object.conflictResolution ?? 0;
    message.autofillMissingUserIdColumns = object.autofillMissingUserIdColumns ?? false;
    message.enableSubscriptions = object.enableSubscriptions ?? false;
    message.aclWorld = object.aclWorld?.map((e) => e) || [];
    message.aclAuthenticated = object.aclAuthenticated?.map((e) => e) || [];
    message.excludedColumns = object.excludedColumns?.map((e) => e) || [];
    message.createAccessRule = object.createAccessRule ?? "";
    message.readAccessRule = object.readAccessRule ?? "";
    message.updateAccessRule = object.updateAccessRule ?? "";
    message.deleteAccessRule = object.deleteAccessRule ?? "";
    message.schemaAccessRule = object.schemaAccessRule ?? "";
    message.expand = object.expand?.map((e) => e) || [];
    message.listingHardLimit = object.listingHardLimit ?? 0n;
    return message;
  },
};

function createBaseJsonSchemaConfig(): JsonSchemaConfig {
  return {};
}

export const JsonSchemaConfig: MessageFns<JsonSchemaConfig> = {
  encode(message: JsonSchemaConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined && message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.schema !== undefined && message.schema !== "") {
      writer.uint32(18).string(message.schema);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JsonSchemaConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJsonSchemaConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.schema = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JsonSchemaConfig {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      schema: isSet(object.schema) ? globalThis.String(object.schema) : undefined,
    };
  },

  toJSON(message: JsonSchemaConfig): unknown {
    const obj: any = {};
    if (message.name !== undefined && message.name !== "") {
      obj.name = message.name;
    }
    if (message.schema !== undefined && message.schema !== "") {
      obj.schema = message.schema;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JsonSchemaConfig>, I>>(base?: I): JsonSchemaConfig {
    return JsonSchemaConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JsonSchemaConfig>, I>>(object: I): JsonSchemaConfig {
    const message = createBaseJsonSchemaConfig();
    message.name = object.name ?? "";
    message.schema = object.schema ?? "";
    return message;
  },
};

function createBaseDatabaseConfig(): DatabaseConfig {
  return {};
}

export const DatabaseConfig: MessageFns<DatabaseConfig> = {
  encode(message: DatabaseConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined && message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DatabaseConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDatabaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DatabaseConfig {
    return { name: isSet(object.name) ? globalThis.String(object.name) : undefined };
  },

  toJSON(message: DatabaseConfig): unknown {
    const obj: any = {};
    if (message.name !== undefined && message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DatabaseConfig>, I>>(base?: I): DatabaseConfig {
    return DatabaseConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DatabaseConfig>, I>>(object: I): DatabaseConfig {
    const message = createBaseDatabaseConfig();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseConfig(): Config {
  return {
    email: undefined,
    server: undefined,
    auth: undefined,
    jobs: undefined,
    databases: [],
    recordApis: [],
    schemas: [],
  };
}

export const Config: MessageFns<Config> = {
  encode(message: Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== undefined) {
      EmailConfig.encode(message.email, writer.uint32(18).fork()).join();
    }
    if (message.server !== undefined) {
      ServerConfig.encode(message.server, writer.uint32(26).fork()).join();
    }
    if (message.auth !== undefined) {
      AuthConfig.encode(message.auth, writer.uint32(34).fork()).join();
    }
    if (message.jobs !== undefined) {
      JobsConfig.encode(message.jobs, writer.uint32(42).fork()).join();
    }
    for (const v of message.databases) {
      DatabaseConfig.encode(v!, writer.uint32(66).fork()).join();
    }
    for (const v of message.recordApis) {
      RecordApiConfig.encode(v!, writer.uint32(90).fork()).join();
    }
    for (const v of message.schemas) {
      JsonSchemaConfig.encode(v!, writer.uint32(170).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = EmailConfig.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.server = ServerConfig.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.auth = AuthConfig.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.jobs = JobsConfig.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.databases.push(DatabaseConfig.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.recordApis.push(RecordApiConfig.decode(reader, reader.uint32()));
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.schemas.push(JsonSchemaConfig.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Config {
    return {
      email: isSet(object.email) ? EmailConfig.fromJSON(object.email) : undefined,
      server: isSet(object.server) ? ServerConfig.fromJSON(object.server) : undefined,
      auth: isSet(object.auth) ? AuthConfig.fromJSON(object.auth) : undefined,
      jobs: isSet(object.jobs) ? JobsConfig.fromJSON(object.jobs) : undefined,
      databases: globalThis.Array.isArray(object?.databases)
        ? object.databases.map((e: any) => DatabaseConfig.fromJSON(e))
        : [],
      recordApis: globalThis.Array.isArray(object?.recordApis)
        ? object.recordApis.map((e: any) => RecordApiConfig.fromJSON(e))
        : globalThis.Array.isArray(object?.record_apis)
        ? object.record_apis.map((e: any) => RecordApiConfig.fromJSON(e))
        : [],
      schemas: globalThis.Array.isArray(object?.schemas)
        ? object.schemas.map((e: any) => JsonSchemaConfig.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Config): unknown {
    const obj: any = {};
    if (message.email !== undefined) {
      obj.email = EmailConfig.toJSON(message.email);
    }
    if (message.server !== undefined) {
      obj.server = ServerConfig.toJSON(message.server);
    }
    if (message.auth !== undefined) {
      obj.auth = AuthConfig.toJSON(message.auth);
    }
    if (message.jobs !== undefined) {
      obj.jobs = JobsConfig.toJSON(message.jobs);
    }
    if (message.databases?.length) {
      obj.databases = message.databases.map((e) => DatabaseConfig.toJSON(e));
    }
    if (message.recordApis?.length) {
      obj.recordApis = message.recordApis.map((e) => RecordApiConfig.toJSON(e));
    }
    if (message.schemas?.length) {
      obj.schemas = message.schemas.map((e) => JsonSchemaConfig.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Config>, I>>(base?: I): Config {
    return Config.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Config>, I>>(object: I): Config {
    const message = createBaseConfig();
    message.email = (object.email !== undefined && object.email !== null)
      ? EmailConfig.fromPartial(object.email)
      : undefined;
    message.server = (object.server !== undefined && object.server !== null)
      ? ServerConfig.fromPartial(object.server)
      : undefined;
    message.auth = (object.auth !== undefined && object.auth !== null)
      ? AuthConfig.fromPartial(object.auth)
      : undefined;
    message.jobs = (object.jobs !== undefined && object.jobs !== null)
      ? JobsConfig.fromPartial(object.jobs)
      : undefined;
    message.databases = object.databases?.map((e) => DatabaseConfig.fromPartial(e)) || [];
    message.recordApis = object.recordApis?.map((e) => RecordApiConfig.fromPartial(e)) || [];
    message.schemas = object.schemas?.map((e) => JsonSchemaConfig.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
