// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableIndex } from "./TableIndex";

export type AlterIndexRequest = { source_schema: TableIndex, target_schema: TableIndex, dry_run: boolean | null, };
