// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";

export type AlterTableOperation = { "RenameTableTo": { name: string, } } | { "AddColumn": { column: Column, } } | { "DropColumn": { name: string, } } | { "AlterColumn": { name: string, column: Column, } } | { "ChangeColumnOrder": { names: Array<string>, } };
