// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlterTableOperation } from "./AlterTableOperation";
import type { Table } from "./Table";

/**
 * Request for altering `TABLE` schema.
 */
export type AlterTableRequest = { source_schema: Table, operations: Array<AlterTableOperation>, dry_run: boolean | null, };
