// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangePasswordRequest = { old_password: string, new_password: string, new_password_repeat: string, 
/**
 * Success (and error if err_redirect_uri not present) redirect target for non-JSON requests.
 */
redirect_uri: string | null, 
/**
 * Error redirect target for non-JSON requests.
 */
err_redirect_uri: string | null, };
