// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColumnOrder = { column_name: string, ascending: boolean | null, nulls_first: boolean | null, };
