// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnAffinityType } from "./ColumnAffinityType";
import type { ColumnDataType } from "./ColumnDataType";
import type { ColumnOption } from "./ColumnOption";

export type Column = { name: string, type_name: string, data_type: ColumnDataType, affinity_type: ColumnAffinityType, options: Array<ColumnOption>, };
