// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Different affinity types in SQLite will lead to different preferences in interpreting input
 * literals. For example, a column with REAL preference, will store any input but try to convert
 * strings into REAL when possible.
 */
export type ColumnAffinityType = "Text" | "Integer" | "Real" | "Blob" | "Numeric";
