// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Table } from "./Table";

export type CreateTableRequest = { schema: Table, dry_run: boolean | null, };
