// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqlValue } from "./SqlValue";

export type DeleteRowRequest = { primary_key_column: string, 
/**
 * The primary key value.
 */
value: SqlValue, };
