// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqlValue } from "./SqlValue";

export type InsertRowRequest = { 
/**
 * Row data, which is expected to be a map from column name to value.
 */
row: { [key in string]: SqlValue }, };
