// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WasmModuleEntry } from "./WasmModuleEntry";

export type ListWasmModulesResponse = { modules: Array<WasmModuleEntry>, };
