// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserJson } from "./UserJson";

export type ListUsersResponse = { total_row_count: bigint, users: Array<UserJson>, };
