// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonSchema } from "./JsonSchema";

export type ListJsonSchemasResponse = { schemas: Array<JsonSchema>, };
