// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { SqlValue } from "./SqlValue";

export type ListRowsResponse = { 
/**
 * Column schema.
 */
columns: Array<Column>, 
/**
 * Actual row data.
 */
rows: Array<Array<SqlValue>>, 
/**
 * Total number of records.
 */
total_row_count: bigint, 
/**
 * Next cursor for pagination.
 */
cursor: string | null, };
