// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginStatusResponse = { auth_token: string | null, refresh_token: string | null, csrf_token: string | null, };
