// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseType } from "./ResponseType";

export type LoginMfaRequest = { mfa_token: string, totp: string | null, redirect_uri: string | null, mfa_redirect_uri: string | null, response_type: ResponseType | null, pkce_code_challenge: string | null, };
