// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Operation = { "Create": { api_name: string, value: JsonValue, } } | { "Update": { api_name: string, record_id: string, value: JsonValue, } } | { "Delete": { api_name: string, record_id: string, } };
