// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadFilesQuery = { pk_column: string, pk_value: string, file_column_name: string, file_name: string | null, };
