// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestOtpRequest = { email_or_username: string, redirect_uri: string | null, } | { email: string, redirect_uri: string | null, } | { username: string, redirect_uri: string | null, };
