// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionResult } from "./TransactionResult";

export type TransactionResponse = { 
/**
 * A 1:1 mapping of opreations to results.
 */
results: Array<TransactionResult>, };
