// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqlValue } from "./SqlValue";

export type UpdateRowRequest = { primary_key_column: string, primary_key_value: SqlValue, 
/**
 * Row data, which is expected to be a map from column name to value.
 *
 * Note that the row is represented as a map to allow selective cells as opposed to
 * Vec<SqlValue>. Absence is different from setting a column to NULL.
 */
row: { [key in string]: SqlValue }, };
