// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserJson = { id: string, email: string, verified: boolean, admin: boolean, provider_id: bigint, provider_user_id: string | null, created: bigint, updated: bigint, };
