[package]
name = "trail-auth-component"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
trailbase-wasm = { workspace = true }

[build-dependencies]
trailbase-build = { workspace = true }
