apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5hcmdpYWdvLnJ1Ijp7InVzZXJuYW1lIjoicmVnaXN0cnktdXNlciIsInBhc3N3b3JkIjoiWVZnREk4clZscG1wbm9wZXZtMDVFdDJ3MEtucXlyVGgiLCJhdXRoIjoiY21WbmFYTjBjbmt0ZFhObGNqcFpWbWRFU1RoeVZteHdiWEJ1YjNCbGRtMHdOVVYwTW5jd1MyNXhlWEpVYUE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  namespace: argiago
  name: registry-auth-client-secret
type: kubernetes.io/dockerconfigjson