apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-issuer
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ./.helm/templates
    kompose.service.expose: author-switcher.argiago.test
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: author-switcher-secret
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: author-switcher
  name: author-switcher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: author-switcher
  strategy: {}
  template:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: cert-manager-issuer
        kompose.cmd: kompose convert -f docker-compose.dev.yml -o ./.helm/templates
        kompose.service.expose: author-switcher.argiago.test
        kompose.service.expose.ingress-class-name: nginx
        kompose.service.expose.tls-secret: author-switcher-secret
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/argiago-network: "true"
        io.kompose.service: author-switcher
    spec:
      containers:
        - env:
            - name: AUDIENCE
              value: author-switcher
            - name: CLIENT_ID
              value: author-switcher
            - name: CLIENT_SECRET
              value: UeBfjDJoOhKXiH4yOEHC24qoh2YLIh1f
            - name: HOST_URL
              value: https://keycloak.argiago.test
            - name: ISSUER
              value: https://keycloak.argiago.test/realms/argiago-test
            - name: REALM
              value: argiago-test
            - name: REQWEST_CONTENT_TYPE
              value: form
            - name: TOKEN_URL
              value: https://keycloak.argiago.test/realms/argiago-test/protocol/openid-connect/token
          image: {{ .Values.werf.image.author_switcher }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/healthcheck
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
          name: author-switcher
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
