apiVersion: v1
kind: Service
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-issuer
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ./.helm/templates
    kompose.service.expose: avatar-downloader.argiago.test
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: avatar-downloader-secret
    kompose.version: 1.28.0 (HEAD)
    kompose.volume.type: hostPath
  creationTimestamp: null
  labels:
    io.kompose.service: avatar-downloader
  name: avatar-downloader
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: avatar-downloader
status:
  loadBalancer: {}
