version: '3.8'

services:
  comment-requester:
    container_name: comment-requester
    image: "{{ .Values.werf.image.comment_requester }}"
    labels:
      kompose.service.expose: "comment-requester.argiago.test"
      kompose.service.expose.tls-secret: "comment-requester-secret"
      cert-manager.io/cluster-issuer: cert-manager-issuer
      kompose.service.expose.ingress-class-name: "nginx"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthcheck" ]
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      POST_SITE: https://${POST_REQUESTER_SERVICE_HOST}:${POST_REQUESTER_SERVICE_PORT}
      ISSUER: https://keycloak.argiago.test/realms/argiago-test

      DB_URL: mongodb://root:root@${MONGO_SERVICE_HOST}:${MONGO_SERVICE_PORT}
      DB_NAME: comment_store
      COLLECTION_NAME: comment
    ports:
      - "80:8080"
    networks:
      - argiago-network
  
networks:
  argiago-network:
    name: argiago-network
    external: true
      