version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    labels:
      kompose.controller.type: "statefulset"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - argiago-network

  rabbitmq:
    image: rabbitmq:3.11.8-management-alpine
    container_name: rabbitmq
    labels:
      kompose.controller.type: "statefulset"
      kompose.service.expose: "rabbitmq.argiago.test"
      kompose.service.expose.tls-secret: "rabbitmq-secret"
      cert-manager.io/cluster-issuer: cert-manager-issuer
      kompose.service.expose.ingress-class-name: "nginx"
    ports:
      - 80:15672
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/:rw
      - rabbitmq_log:/var/log/rabbitmq/:rw
    networks:
      - argiago-network

volumes:
  mongodb:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local

networks:
  argiago-network:
    name: argiago-network