version: '3.8'

services:
  avatar-downloader:
    container_name: avatar-downloader
    image: "{{ .Values.werf.image.avatar_downloader }}"
    labels:
      kompose.service.expose: "avatar-downloader.argiago.test"
      kompose.service.expose.tls-secret: "avatar-downloader-secret"
      cert-manager.io/cluster-issuer: cert-manager-issuer
      kompose.service.expose.ingress-class-name: "nginx"
      kompose.volume.type: hostPath
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthcheck" ]
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - /tmp/static:/tmp/static
    ports:
      - "80:8080"
    networks:
      - argiago-network
  
networks:
  argiago-network:
    name: argiago-network
    external: true
      